app = "kirim"
primary_region = "sin"

[build]
  dockerfile = "Dockerfile"

[env]
  APP_PORT = "3000"
  APP_DEBUG = "true"
  APP_OS = "Chrome"
  APP_ACCOUNT_VALIDATION = "false"

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 1
  processes = ["app"]

[mounts]
  source = "whatsapp_data"
  destination = "/app/storages"

[[vm]]
  size = "shared-cpu-1x"
  memory = 512
