name: Deploy WhatsApp Gateway to Fly.io

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Flyctl
        uses: superfly/flyctl-actions/setup-flyctl@master

      - name: Ensure Fly App & Volume Exist
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
        run: |
          APP_NAME="kirim"
          REGION="sin"
          VOLUME_NAME="whatsapp_data"

          # Cek apakah aplikasi sudah ada
          if ! flyctl apps list | grep -q "^$APP_NAME"; then
            echo "Creating Fly app: $APP_NAME"
            flyctl apps create "$APP_NAME"
          else
            echo "App $APP_NAME already exists."
          fi

          # Cek apakah volume sudah ada
          if ! flyctl volumes list --app "$APP_NAME" | grep -q "$VOLUME_NAME"; then
            echo "Creating volume $VOLUME_NAME..."
            flyctl volumes create "$VOLUME_NAME" --region "$REGION" --size 1 --app "$APP_NAME --yes"
          else
            echo "Volume $VOLUME_NAME already exists."
          fi

      - name: Deploy to Fly.io
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
          APP_BASIC_AUTH: ${{ secrets.APP_BASIC_AUTH }}
        run: |
          flyctl secrets set APP_BASIC_AUTH="$APP_BASIC_AUTH" --app kirim
          flyctl deploy --remote-only --app kirim
